[project]
name = "altiummcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.5.0",
    "pillow>=11.1.0",
    "pywin32>=310",
]
