"""Merge the bridge's DelphiScript units into one file for RunScriptFile.

Running a script PROJECT (ScriptingSystem:RunScript with ProjectName) makes
Altium create hidden copies of the forms in every script project on the
user's menus and never free them, about 100 window handles per call. Running
a single script FILE does not. A single file must define each routine before
it is used, so the units are split into top-level chunks and ordered:
global var/const blocks first, then routines with their callees first.
"""

import re
from pathlib import Path

_ROUTINE = re.compile(r"^(?:function|procedure)\s+([A-Za-z_]\w*)", re.I)
_NOISE = re.compile(r"//[^\n]*|\{[^}]*\}|\(\*.*?\*\)|'(?:[^']|'')*'", re.S)


def _is_section(line):
    return not line[:1].isspace() and line.strip().lower() in ("var", "const")


def _chunks(path):
    """Top-level chunks of one unit: ('decl', None, text) for global var/const
    blocks and ('routine', name, text) for routines (comments above them
    included). Routines start at column 0 and end at the first column-0
    'end;' after their column-0 'begin'."""
    lines = path.read_text(encoding="latin-1").replace("\r\n", "\n").split("\n")
    out, pending, i = [], [], 0
    while i < len(lines):
        line = lines[i]
        m = _ROUTINE.match(line)
        if m:
            j = i
            while j < len(lines) and not re.match(r"begin\b", lines[j], re.I):
                j += 1
            j += 1
            while j < len(lines) and not re.match(r"end;", lines[j], re.I):
                j += 1
            if j >= len(lines):
                raise ValueError(f"{path.name}:{i + 1}: no column-0 'end;' closing {m.group(1)}")
            out.append(("routine", m.group(1).lower(), "\n".join(pending + lines[i:j + 1])))
            pending, i = [], j + 1
        elif _is_section(line):
            j = i + 1
            while j < len(lines) and not _ROUTINE.match(lines[j]) and not _is_section(lines[j]):
                j += 1
            out.append(("decl", None, "\n".join(pending + lines[i:j])))
            pending, i = [], j
        else:
            pending.append(line)
            i += 1
    if _NOISE.sub(" ", "\n".join(pending)).strip():
        raise ValueError(f"{path.name}: code outside any routine or var/const block")
    return out


def bundle_text(units):
    """One script file from the given unit paths (in project order)."""
    decls, routines = [], []
    for path in units:
        for kind, name, text in _chunks(Path(path)):
            (decls if kind == "decl" else routines).append((name, text, Path(path).name))
    index = {name: n for n, (name, _, _) in enumerate(routines)}
    if len(index) != len(routines):
        raise ValueError("a routine name is defined twice")
    calls = []
    for name, text, _ in routines:
        words = {w.lower() for w in re.findall(r"[A-Za-z_]\w*", _NOISE.sub(" ", text))}
        calls.append(sorted(index[w] for w in words if w in index and w != name))

    order, state = [], {}

    def visit(n, trail):
        if state.get(n) == "done":
            return
        if state.get(n) == "busy":
            raise ValueError("routines call each other in a cycle: " +
                             " -> ".join(routines[k][0] for k in trail + [n]))
        state[n] = "busy"
        for k in calls[n]:
            visit(k, trail + [n])
        state[n] = "done"
        order.append(n)

    for n in range(len(routines)):
        visit(n, [])
    parts = ["// Generated by script_bundle.py from the Altium_API units - do not edit."]
    parts += [f"// --- {src}\n{text}" for _, text, src in decls]
    parts += [f"// --- {routines[n][2]}\n{routines[n][1]}" for n in order]
    return "\r\n".join("\n\n".join(parts).split("\n")) + "\r\n"


def project_units(project_file):
    """Unit paths listed in a .PrjScr, in project order."""
    project_file = Path(project_file)
    text = project_file.read_text(encoding="latin-1")
    return [project_file.parent / p.strip()
            for p in re.findall(r"^DocumentPath=(.+?)\s*$", text, re.M)
            if p.strip().lower().endswith(".pas")]


def ensure_bundle(project_file, out_file):
    """(Re)build out_file when it is missing or older than a unit. Returns it."""
    units = project_units(project_file)
    out_file = Path(out_file)
    newest = max(p.stat().st_mtime for p in units + [Path(project_file), Path(__file__)])
    if not out_file.exists() or out_file.stat().st_mtime < newest:
        tmp = out_file.with_suffix(".tmp")
        tmp.write_bytes(bundle_text(units).encode("latin-1"))
        tmp.replace(out_file)
    return out_file
